= Prueba Tecnica Angular HARUK

== Siga las instrucciones 

*Si decide usar git:* Cree una rama (branch) del repositorio actual con su nombre
            `git checkout -b jhon_doe`

*Si decide enviar los archivos por correo:* Descargue el repositorio, modifiquelo localmente y envienos un correo a info@haruk.co con la solución indicando su nombre en el asunto.

Ejecute `npm start` en la consola y siga las instrucciones de los dos casos presentados (basico, intermedio).

No hay soluciones correctas o incorrectas, solo queremos conocer la forma de abordar los problemas y el estilo de codigoo usado para la solución.

Gracias por tu tiempo!

This project was generated with [Angular CLI](https://github.com/angular/angular-cli) version 8.3.20.

== Development server

Run `ng serve` for a dev server.
Navigate to `http://localhost:4200/`. The app will automatically reload if you change any of the source files.

== Code scaffolding

Run `ng generate component component-name` to generate a new component.
You can also use `ng generate directive|pipe|service|class|guard|interface|enum|module`.

== Build

Run `ng build` to build the project.
The build artifacts will be stored in the `dist/` directory.
Use the `--prod` flag for a production build.

== Running unit tests

Run `ng test` to execute the unit tests via [Karma](https://karma-runner.github.io).

== Running end-to-end tests

Run `ng e2e` to execute the end-to-end tests via [Protractor](http://www.protractortest.org/).

== Further help

To get more help on the Angular CLI use `ng help` or go check out the [Angular CLI README](https://github.com/angular/angular-cli/blob/master/README.md).
